# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'https-lenpaul-github-io-lagrange'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: ''

menu:
- {name: 'Course Demo', path: 'journal', url: 'dyn-sys.html'}
- {name: 'Remote Lerning', path: 'journal', url: 'video-lecture.html'}
- {name: 'Teaching history', path: 'menu', url: 'teaching-history.html'}
- {name: 'Bio', path: 'menu', url: 'bio.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'github', link: 'https://www.github.com/inuritdino'}
- {icon: 'linkedin', link: 'http://www.linkedin.com/in/ilyapotapov/'}
# - {icon: 'rss-square', link: '/rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy:'

post_date_prefix: 'Written on'
